In [24]:
from  itertools import combinations
import numpy as np

In [25]:
general_population =[8,3,1,11,4,7]

In [26]:
## Выбираем выборки размера 2 из генеральной совокупности
samples =list(combinations(general_population,2))

In [27]:
samples

[(8, 3),
 (8, 1),
 (8, 11),
 (8, 4),
 (8, 7),
 (3, 1),
 (3, 11),
 (3, 4),
 (3, 7),
 (1, 11),
 (1, 4),
 (1, 7),
 (11, 4),
 (11, 7),
 (4, 7)]

In [28]:
len(samples)

15

In [29]:
## Среднее значение генеральной совокупности
Y_mean = np.array(general_population).mean()
print(Y_mean)

5.666666666666667


In [41]:
# Рассчитываем среднее значение для каждой выборки
y_means =np.zeros(len(samples))
for i, sample in enumerate(samples):
    y_means[i] =np.array(sample).mean()

In [42]:
y_means

array([5.5, 4.5, 9.5, 6. , 7.5, 2. , 7. , 3.5, 5. , 6. , 2.5, 4. , 7.5,
       9. , 5.5])

In [31]:
# Выборочное среднее
y_means.mean()

5.666666666666667

In [32]:
#Выборочное среднее равно среднему генеральной совокупности
Y_mean==y_means.mean()

True

In [33]:
# Дисперсия генеральной совокупности
Y_var = np.array(general_population).var(ddof=1)

In [34]:
# Дисперсия среднего для простой случайной выборки размера 2
var_v =np.sum(np.power((y_means-Y_mean),2))/(len(samples))
print(var_v)

4.488888888888889


In [35]:
## Значение дисперсия среднего для простой случайной выборки размера 2 по теореме 2.2

In [36]:
(Y_var/2)*(1-2/len(general_population))

4.488888888888889

In [44]:
 ## Рассчитываем стандартную ошибку
y_vars =np.zeros(len(samples))
for i, sample in enumerate(samples):
    y_vars[i]=np.sum(np.power(sample - y_means[i],2))

In [50]:
y_vars

array([12.5, 24.5,  4.5,  8. ,  0.5,  2. , 32. ,  0.5,  8. , 50. ,  4.5,
       18. , 24.5,  8. ,  4.5])

In [49]:
np.sum(y_vars)

202.0

In [46]:
y_vars.mean()

13.466666666666667

In [47]:
Y_var

13.466666666666665

In [43]:
y_means[0]

5.5

In [40]:
sample - y_means[i]

array([4., 7.])