# Numpy

In [1]:
import numpy as np

## Arrays creation

In [2]:
x = np.array([1, 2, 3, 5, 4])

In [3]:
x

array([1, 2, 3, 5, 4])

In [4]:
x.dtype

dtype('int32')

In [5]:
x = np.array([1, 2, 3, 5, 4], dtype=np.float64)

In [6]:
x

array([1., 2., 3., 5., 4.])

In [7]:
x.dtype

dtype('float64')

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros([5, 5], dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.ones((4, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.full((3, 5), 2019)

array([[2019, 2019, 2019, 2019, 2019],
       [2019, 2019, 2019, 2019, 2019],
       [2019, 2019, 2019, 2019, 2019]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [15]:
np.arange(99, 32, -3)

array([99, 96, 93, 90, 87, 84, 81, 78, 75, 72, 69, 66, 63, 60, 57, 54, 51,
       48, 45, 42, 39, 36, 33])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0, 2*np.pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [18]:
# Uniform
np.random.random((3, 3))

array([[0.67952962, 0.60219278, 0.79678775],
       [0.67132844, 0.1677069 , 0.64149243],
       [0.05361113, 0.78791375, 0.37408809]])

In [19]:
# Normal (Gaussian) distribution
np.random.normal(0, 1, (5, 3))

array([[-0.79855415,  0.09394019,  0.42248706],
       [ 1.27591978,  1.09638599,  1.69794281],
       [ 1.85127454, -0.99228582, -0.57362591],
       [ 0.96081401, -0.22243654, -0.35772245],
       [-1.27141519,  0.84021213,  0.26478985]])

In [20]:
snd = np.random.normal(0, 1, 1000)
print(snd.mean())
print(snd.std())

-0.035960833740393154
1.019607622908529


In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(4, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.eye(4, 10).shape

(4, 10)

In [24]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

## Arrays indexing

In [25]:
x = np.arange(10)

In [26]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[3]

3

In [28]:
x[-1], x[-3]

(9, 7)

In [29]:
x = np.random.randint(10, size = (3, 4))
x

array([[2, 3, 8, 2],
       [1, 5, 3, 6],
       [9, 1, 0, 4]])

In [30]:
x[0, 0]

2

In [31]:
x[0, 2]

8

In [32]:
x[-1, -1]

4

In [33]:
x[0, 0] = 11

In [34]:
x

array([[11,  3,  8,  2],
       [ 1,  5,  3,  6],
       [ 9,  1,  0,  4]])

In [35]:
x2 = x

In [36]:
x2[0, 0] = 13

In [37]:
print(x)
print(x2)

[[13  3  8  2]
 [ 1  5  3  6]
 [ 9  1  0  4]]
[[13  3  8  2]
 [ 1  5  3  6]
 [ 9  1  0  4]]


In [38]:
x3 = x.copy()
x3[0, 0] = 1333

In [39]:
print(x)
print(x2)
print(x3)

[[13  3  8  2]
 [ 1  5  3  6]
 [ 9  1  0  4]]
[[13  3  8  2]
 [ 1  5  3  6]
 [ 9  1  0  4]]
[[1333    3    8    2]
 [   1    5    3    6]
 [   9    1    0    4]]


In [40]:
x is x2

True

In [41]:
x is x3

False

## Arrays slicing

In [42]:
x = np.arange(10)

In [43]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5]

array([0, 1, 2, 3, 4])

In [45]:
x[5:]

array([5, 6, 7, 8, 9])

In [46]:
x[5:-1]

array([5, 6, 7, 8])

In [47]:
x[4:7]

array([4, 5, 6])

In [48]:
x[::2]

array([0, 2, 4, 6, 8])

In [49]:
x[3:-1:3]

array([3, 6])

In [50]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Arrays reshaping

In [51]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
x = x.reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
x = x.reshape((2, 3, 2))
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [54]:
x = x.reshape((12, ))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
x = x.reshape((6, -1))
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [56]:
x = x.reshape((5, -1))
x

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [57]:
x = x.reshape((3, 4))
x[:2, :3] = np.ones((2, 3))
x

array([[ 1,  1,  1,  3],
       [ 1,  1,  1,  7],
       [ 8,  9, 10, 11]])

slice $=$ view

slice $\neq$ copy

In [58]:
x[:2, :2] = np.eye(2)*1333
x

array([[1333,    0,    1,    3],
       [   0, 1333,    1,    7],
       [   8,    9,   10,   11]])

## Arrays concatenation

In [59]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [60]:
z = np.concatenate([x, y])
z

array([1, 2, 3, 4, 5, 6])

In [61]:
g = np.array([[1, 2, 3],
              [4, 5, 6]])
g

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([g, g])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([g, g], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
np.vstack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [66]:
np.hstack([g, x[:-1].reshape([2, 1])])

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

## Calculations on arrays

In [67]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
x - 9

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [70]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [73]:
2 ** x

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [74]:
(x + 1) / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [75]:
2 / (x + 1)

array([2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
       0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ])

In [76]:
y = np.arange(10, 20)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [77]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [78]:
x + y

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [79]:
x * y

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [80]:
x / y

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [81]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
x * x

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [83]:
x ** x

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]], dtype=int32)

In [84]:
np.dot(x, x)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [85]:
x @ x

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [86]:
x.min()

0

In [87]:
x.max()

8

In [88]:
x.mean()

4.0

In [89]:
x.std()

2.581988897471611

In [90]:
x.sum()

36

In [91]:
(x + 1).prod()

362880

In [92]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
np.add.accumulate(x)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [94]:
np.add.accumulate(x, axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [95]:
np.add.accumulate(x.ravel())

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [96]:
np.subtract.accumulate(x)

array([[  0,   1,   2],
       [ -3,  -3,  -3],
       [ -9, -10, -11]], dtype=int32)

In [97]:
x ** 2 - 4 * x + 1

array([[ 1, -2, -3],
       [-2,  1,  6],
       [13, 22, 33]])

In [98]:
x = np.random.randint(0, 100, (5, 5))
x

array([[ 5, 34, 78, 69, 33],
       [22, 53, 91, 50, 85],
       [88, 95, 59, 20, 38],
       [20, 70, 26, 84, 56],
       [54, 44, 81, 51, 11]])

In [99]:
x.max(), x.argmax()

(95, 11)

In [100]:
x.min(), x.argmin()

(5, 0)

## Masks

In [101]:
x > 50

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [ True,  True,  True, False, False],
       [False,  True, False,  True,  True],
       [ True, False,  True,  True, False]])

In [102]:
x = x.ravel()
x

array([ 5, 34, 78, 69, 33, 22, 53, 91, 50, 85, 88, 95, 59, 20, 38, 20, 70,
       26, 84, 56, 54, 44, 81, 51, 11])

In [103]:
x > 50

array([False, False,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True, False,
        True,  True,  True, False,  True,  True, False])

In [104]:
x[x > 50]

array([78, 69, 53, 91, 85, 88, 95, 59, 70, 84, 56, 54, 81, 51])

In [105]:
x[(x > 50) & (x < 75)] # and

array([69, 53, 59, 70, 56, 54, 51])

In [106]:
x[(x > 90) | (x < 10)] # or

array([ 5, 91, 95])

In [107]:
x[~(x > 50)] #not

array([ 5, 34, 33, 22, 50, 20, 38, 20, 26, 44, 11])