In [2]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns; sns.set(style='whitegrid')

In [3]:
N = 6
pop = np.array((8, 3, 1, 11, 4, 7))
n = 2

In [5]:
sp.special.comb(N, n)

15.0

In [6]:
Y_mean = pop.mean()
Y_mean

5.666666666666667

In [7]:
from itertools import combinations

In [10]:
means = []
for sample in combinations(pop, n):
    sample_mean = np.array(sample).mean()
    means.append(sample_mean)
    print(sample, sample_mean)
np.array(means).mean()

(8, 3) 5.5
(8, 1) 4.5
(8, 11) 9.5
(8, 4) 6.0
(8, 7) 7.5
(3, 1) 2.0
(3, 11) 7.0
(3, 4) 3.5
(3, 7) 5.0
(1, 11) 6.0
(1, 4) 2.5
(1, 7) 4.0
(11, 4) 7.5
(11, 7) 9.0
(4, 7) 5.5


5.666666666666667

# variance

In [11]:
pop.std()

3.34995854037363

In [12]:
pop.var()

11.222222222222221

# Numpy magic

In [20]:
pop

array([ 8,  3,  1, 11,  4,  7])

In [21]:
pop - pop.mean()

array([ 2.33333333, -2.66666667, -4.66666667,  5.33333333, -1.66666667,
        1.33333333])

In [22]:
(pop - pop.mean())**2

array([ 5.44444444,  7.11111111, 21.77777778, 28.44444444,  2.77777778,
        1.77777778])

In [23]:
((pop - pop.mean())**2).sum()

67.33333333333333

# ok going back

In [19]:
var = ((pop - pop.mean())**2).sum()/pop.size
var

11.222222222222221

In [24]:
pop.var()

11.222222222222221

In [26]:
s2 = pop.size * pop.var() / (pop.size - 1)
s2

13.466666666666665

In [27]:
def svar(arr):
    return arr.size * arr.var() / (arr.size - 1)
svar(pop)

13.466666666666665

## E(s2) = S2

In [28]:
S2 = svar(pop)
S2

13.466666666666665

In [31]:
svars = []
for sample in combinations(pop, n):
    sample_svar = svar(np.array(sample))
    svars.append(sample_svar)
    print(sample, sample_svar)
np.array(svars).mean()

(8, 3) 12.5
(8, 1) 24.5
(8, 11) 4.5
(8, 4) 8.0
(8, 7) 0.5
(3, 1) 2.0
(3, 11) 32.0
(3, 4) 0.5
(3, 7) 8.0
(1, 11) 50.0
(1, 4) 4.5
(1, 7) 18.0
(11, 4) 24.5
(11, 7) 8.0
(4, 7) 4.5


13.466666666666667

### test

In [32]:
vars_ = []
print(pop.var())
for sample in combinations(pop, n):
    sample_vars_ = np.array(sample).var()
    vars_.append(sample_vars_)
    print(sample, sample_vars_)
np.array(vars_).mean()

11.222222222222221
(8, 3) 6.25
(8, 1) 12.25
(8, 11) 2.25
(8, 4) 4.0
(8, 7) 0.25
(3, 1) 1.0
(3, 11) 16.0
(3, 4) 0.25
(3, 7) 4.0
(1, 11) 25.0
(1, 4) 2.25
(1, 7) 9.0
(11, 4) 12.25
(11, 7) 4.0
(4, 7) 2.25


6.733333333333333

# Confidence intervals

## Simple example

In [33]:
mu = 100
sigma = 10

n = 30
y = np.random.normal(mu, sigma, n)
y

array([104.84521299,  92.17629305,  92.07166661, 107.32024853,
       102.45437234, 103.74618465,  99.6961913 , 103.90057932,
        96.42961637, 100.07688298, 103.55905105,  87.14728364,
        96.27384037, 104.73961087,  89.08157635, 101.61617943,
        94.85947194, 111.19016076,  93.35107989,  98.59795116,
        89.10514727,  86.36175079,  89.3889882 , 110.89180226,
        86.41165131, 111.13943769, 107.7188999 ,  91.21205002,
       110.76647973,  84.13116046])

In [34]:
y_mean = y.mean()
y_mean

98.34202737413453

In [35]:
ys2 = svar(y)
ys2

70.68394730396314

In [36]:
ys = np.sqrt(ys2)
ys

8.407374578544905

In [37]:
N = 10000

In [38]:
# Доля отбора
f = n / N
f

0.003

In [39]:
y_mean_std = ys * np.sqrt(1 - f) / np.sqrt(n)
y_mean_std

1.5326653848992529

y_mean +- t * y_mean_std

In [40]:
alpha = 0.95

print(sp.stats.norm.ppf(0.025))
print(sp.stats.norm.ppf(0.975))

-1.9599639845400545
1.959963984540054


In [43]:
print(sp.stats.norm.cdf(2))
print(sp.stats.norm.cdf(-2))
print(sp.stats.norm.cdf(2) - sp.stats.norm.cdf(-2))

0.9772498680518208
0.022750131948179195
0.9544997361036416


In [44]:
sp.stats.norm.ppf((1 + alpha) / 2)

1.959963984540054

In [45]:
sp.stats.norm.ppf((1 - alpha) / 2)

-1.959963984540054

In [46]:
t = sp.stats.norm.ppf((1 + alpha) / 2)
t

1.959963984540054

In [47]:
ci_left = y_mean - t * y_mean_std
ci_right = y_mean + t * y_mean_std

In [48]:
ci_left, ci_right

(95.33805841938077, 101.34599632888829)

In [54]:
alpha = 0.9
t = sp.stats.norm.ppf((1 + alpha) / 2)
ci_left = y_mean - t * y_mean_std
ci_right = y_mean + t * y_mean_std
ci_left, ci_right

(95.82101715688002, 100.86303759138904)

## Complex example

In [56]:
N = 676
n = 50
sample = []
for i in [(42, 23), (41, 4), (36, 1), (32, 1), (29, 1), (27, 2), (23, 1), (19, 1), (16, 2), (15, 2), (14, 1), (11, 1), (10, 1), (9, 1), (7, 1), (6, 3), (5, 2), (4, 1), (3, 1)]:
    sample.append(i)

sample

[(42, 23),
 (41, 4),
 (36, 1),
 (32, 1),
 (29, 1),
 (27, 2),
 (23, 1),
 (19, 1),
 (16, 2),
 (15, 2),
 (14, 1),
 (11, 1),
 (10, 1),
 (9, 1),
 (7, 1),
 (6, 3),
 (5, 2),
 (4, 1),
 (3, 1)]

In [60]:
samp = np.array(sample)
samp

array([[42, 23],
       [41,  4],
       [36,  1],
       [32,  1],
       [29,  1],
       [27,  2],
       [23,  1],
       [19,  1],
       [16,  2],
       [15,  2],
       [14,  1],
       [11,  1],
       [10,  1],
       [ 9,  1],
       [ 7,  1],
       [ 6,  3],
       [ 5,  2],
       [ 4,  1],
       [ 3,  1]])

In [63]:
y_total = (samp[:, 0] * samp[:, 1]).sum()
y_total

1471

In [64]:
y_mean = y_total  / n
y_mean

29.42

In [65]:
y_squared = ((samp[:, 0] ** 2) * samp[:, 1]).sum()
y_squared


54497

In [66]:
y_s2 = (y_squared - (y_total ** 2) / n) / (n - 1)
y_s2

228.98326530612246

In [67]:
y_s = np.sqrt(y_s2)
y_s

15.132193010470177

In [68]:
f = n / N
f

0.07396449704142012

In [70]:
y_mean_std = y_s * np.sqrt(1 - f) / np.sqrt(n)
y_mean_std

2.0593524868601443

In [72]:
alpha = 0.8
t = sp.stats.norm.ppf((1 + alpha) / 2)

ci_left = N * y_mean - t * y_mean_std * N
ci_right = N * y_mean + t * y_mean_std * N

ci_left, ci_right

(18103.843511204403, 21671.9964887956)

# 2.5

In [73]:
y_total = 2138
y_squared = 131_682

In [74]:
y_squared

131682

In [75]:
N = 36

In [76]:
y_mean = y_total / N

In [77]:
y_mean

59.388888888888886

In [78]:
alpha = 0.95
t = sp.stats.norm.ppf((1 + alpha) / 2)
t

1.959963984540054

In [79]:
y_s2 = (y_squared - (y_total ** 2) / N) / (N - 1)
y_s2

134.53015873015892

In [80]:
y_s = np.sqrt(y_s2)

In [81]:
y_s

11.598713667047692

In [86]:
n = ((N**2)*(t**2)*y_s2)/((t**2)*y_s2*N+(200)**2)
n

11.428514060688414

In [88]:
t

1.959963984540054

In [90]:
n =100
a = 9
p = 0.09
q = 1-p

f = 0.2

Rr = 0.046
Rl = 0.157

In [92]:
oR = p + (t*np.sqrt(1-f)*np.sqrt((p*q)/(n-1)) + 1/(2*n))
oL = p - (t*np.sqrt(1-f)*np.sqrt((p*q)/(n-1)) + 1/(2*n))
print(oL, oR)

0.03457830534143856 0.14542169465856142
