In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns; sns.set(style='whitegrid')

In [5]:
fams = sp.random.poisson(1.5, 50) + 1
fams

array([5, 2, 2, 4, 5, 5, 5, 3, 3, 1, 4, 2, 1, 3, 4, 3, 3, 2, 3, 7, 2, 2,
       5, 3, 4, 2, 3, 3, 2, 6, 2, 2, 3, 1, 4, 2, 3, 2, 2, 2, 3, 3, 4, 1,
       6, 3, 3, 2, 2, 2])

In [17]:
def get_earnings(f_size):
    r = min(2, f_size)
    rest = f_size - r
    return r * 800 + np.random.normal(0, 100, 1)[0] + rest * 250


In [19]:
df = pd.DataFrame([(f, get_earnings(f)) for f in fams], columns=['family_size', 'total_income'])
df

family_size  total_income
0             5   2408.293717
1             2   1598.997154
2             2   1512.409549
3             4   2174.455143
4             5   2436.342635
5             5   2407.287009
6             5   2427.143951
7             3   1907.840930
8             3   1874.106515
9             1    682.886851
10            4   1964.245930
11            2   1668.461188
12            1    814.875204
13            3   1797.728154
14            4   2024.496786
15            3   2055.865931
16            3   1950.366910
17            2   1493.567184
18            3   1942.621713
19            7   2942.432124
20            2   1232.354562
21            2   1684.183452
22            5   2507.261708
23            3   1930.972167
24            4   2183.947503
25            2   1507.250114
26            3   1817.288618
27            3   1771.172972
28            2   1669.902307
29            6   2552.203977
30            2   1737.433982
31            2   1578.444537
32            3   1794.327984
33            1    970.147201
34            4   2173.908233
35            2   1800.544547
36            3   1765.020250
37            2   1594.539905
38            2   1482.219354
39            2   1762.469359
40            3   1871.801794
41            3   1878.576010
42            4   2125.414103
43            1    750.014182
44            6   2575.799211
45            3   1760.493821
46            3   1853.880964
47            2   1471.419920
48            2   1832.458713
49            2   1453.163724

In [33]:
R=df['total_income'].sum()/df['family_size'].sum()

In [24]:
N=1000
n=len(df)
f=n/N
f

0.05

In [26]:
x = df['family_size'].values
y = df['total_income'].values

In [28]:
x

array([5, 2, 2, 4, 5, 5, 5, 3, 3, 1, 4, 2, 1, 3, 4, 3, 3, 2, 3, 7, 2, 2,
       5, 3, 4, 2, 3, 3, 2, 6, 2, 2, 3, 1, 4, 2, 3, 2, 2, 2, 3, 3, 4, 1,
       6, 3, 3, 2, 2, 2], dtype=int64)

In [29]:
y

array([2408.29371727, 1598.99715378, 1512.40954873, 2174.45514339,
       2436.34263522, 2407.28700869, 2427.14395085, 1907.84093006,
       1874.10651466,  682.88685054, 1964.24593046, 1668.46118807,
        814.87520431, 1797.72815385, 2024.49678621, 2055.86593117,
       1950.3669101 , 1493.56718363, 1942.62171304, 2942.43212394,
       1232.35456196, 1684.18345178, 2507.26170826, 1930.97216749,
       2183.94750282, 1507.25011384, 1817.28861818, 1771.1729721 ,
       1669.90230709, 2552.20397673, 1737.43398223, 1578.44453735,
       1794.32798409,  970.14720082, 2173.90823326, 1800.5445465 ,
       1765.02025022, 1594.53990545, 1482.21935412, 1762.46935926,
       1871.80179377, 1878.57600996, 2125.41410296,  750.01418183,
       2575.79921068, 1760.4938212 , 1853.880964  , 1471.41992023,
       1832.45871293, 1453.16372436])

In [31]:
x * y

array([12041.46858636,  3197.99430757,  3024.81909746,  8697.82057356,
       12181.71317609, 12036.43504345, 12135.71975424,  5723.52279018,
        5622.31954397,   682.88685054,  7856.98372182,  3336.92237613,
         814.87520431,  5393.18446154,  8097.98714486,  6167.59779352,
        5851.1007303 ,  2987.13436726,  5827.86513912, 20597.02486755,
        2464.70912391,  3368.36690356, 12536.30854131,  5792.91650246,
        8735.79001127,  3014.50022768,  5451.86585453,  5313.51891631,
        3339.80461417, 15313.22386037,  3474.86796445,  3156.88907471,
        5382.98395228,   970.14720082,  8695.63293302,  3601.089093  ,
        5295.06075067,  3189.07981089,  2964.43870824,  3524.93871852,
        5615.4053813 ,  5635.72802987,  8501.65641184,   750.01418183,
       15454.79526408,  5281.48146359,  5561.64289201,  2942.83984047,
        3664.91742586,  2906.32744873])

In [35]:
A=(x*x).sum()*R**2+(y*y).sum()-2*R*(x*y).sum()

In [38]:
B=A/(n-1)
B

192682.5867054219

In [43]:
S=np.sqrt(B)

In [44]:
(np.sqrt(1-f)*S)/(np.sqrt(n)*x.mean())

20.035080488432143

In [45]:
a = [8, 4, 2, 2, 1, 1, 0, 0, 0, 1, 1]
a = np.array(a)
a

array([8, 4, 2, 2, 1, 1, 0, 0, 0, 1, 1])

In [50]:
b = np.arange(0, 11)

In [53]:
N=200
n=20
c = (a * b).sum()

In [54]:
d = c / n
d

2.1

In [55]:
e = d * N
e

420.0

In [67]:
perc = 0.95
t = sp.stats.norm.ppf((1 + perc) / 2)


In [62]:
g = (b*b*a).sum()

In [63]:
y = (c ** 2)/n

In [64]:
s2=(1/(n-1))*(g-y)
s2

8.621052631578948

In [65]:
s = np.sqrt(s2)
s

2.9361629095775577

In [70]:
f

0.1

In [66]:
f=n/N
se = (s* np.sqrt(1-f))/(np.sqrt(n))
se

0.6228542112092144

In [68]:
ci_left = (d - t*se) * N
ci_left

175.8456356821672

In [69]:
ci_right = (d + t*se) * N
ci_right

664.1543643178329

In [71]:
N=140
n=12
a=np.arange(1,11)
b=np.array([4, 2, 2, 1, 1, 0, 0, 0, 1, 1])
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([4, 2, 2, 1, 1, 0, 0, 0, 1, 1]))

In [72]:
f=n/N
f

0.08571428571428572

In [74]:
y_mean = ((a*b).sum())/n
y_mean

3.5

In [76]:
s2=(1/(n-1))*((a*a*b).sum()-(n*y_mean**2))
s2

9.545454545454545

In [77]:
s=np.sqrt(s2)
s

3.089571903266623

In [78]:
y_mean_std=s*np.sqrt(1-f)/np.sqrt(n)
y_mean_std

0.8528028654224417

In [79]:
Y=y_mean*N
Y

490.0

In [80]:
t=sp.stats.norm.ppf((1+perc)/2)
t

1.959963984540054

In [81]:
ci_left = (y_mean-t*y_mean_std)*N
ci_right = (y_mean+t*y_mean_std)*N
ci_left, ci_right

(255.9951937003238, 724.0048062996763)